### ISSUE TITLE
[IMPROVEMENT] Active filter lost when moving in and out of character detail

### ISSUE THREAD

**Issue by Kruptein** [FrederikGoovaerts/Dramatis-Personae#60]
**Reproduction scenario**
1. Set a filter
2. Open a character
3. Click the '<- Campaign' button
4. no longer have a filter applied

**Comment by FrederikGoovaerts** [comment]
The filter state is currently tracked in component state, which is why it resets when the component is unloaded.

My current idea for a solution is this:

- Track filter state in redux
- On updates of filter state, sync filter state to local storage with a debounce
- On application initialization, load filter state from localstorage, we'll assume for this change that a browser is only used by one user
- Filter state contains the contents of the filters and the campaign id
- When visiting another campaign than the one with the currently loaded id in the filter state, clear all filter state in redux and localstorage

This gives the following behaviour:
- Filter state persists within the same campaign and will only ever reset when opening a different campaign
- Filter state persists over reloads on the same browser provided no other campaign is visited in the meanwhile

Storing this on backend for a user would be overkill.

**Comment by FrederikGoovaerts** [comment]
I'm gonna label this an improvement by the way, since the current simpler behaviour was intended.
